// hooks/useFinance.js
import { useState, useEffect } from 'react'
import { 
  collection, 
  doc, 
  getDocs, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  onSnapshot,
  query,
  where,
  orderBy,
  Timestamp
} from 'firebase/firestore'
import { db } from '../config/firebase'

export const useFinance = () => {
  const [transactions, setTransactions] = useState([])
  const [budgets, setBudgets] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  // Kategorie transakcji
  const incomeCategories = [
    { id: 'crop_sales', name: 'Sprzedaż plonów', icon: '🌾', color: '#4caf50' },
    { id: 'animal_sales', name: 'Sprzedaż zwierząt', icon: '🐄', color: '#8bc34a' },
    { id: 'animal_products', name: 'Produkty zwierzęce', icon: '🥛', color: '#2196f3' },
    { id: 'subsidies', name: 'Dotacje', icon: '💰', color: '#ffc107' },
    { id: 'other_income', name: 'Inne przychody', icon: '📈', color: '#9c27b0' }
  ]

  const expenseCategories = [
    { id: 'seeds', name: 'Nasiona', icon: '🌱', color: '#4caf50' },
    { id: 'fertilizers', name: 'Nawozy', icon: '🧪', color: '#ff9800' },
    { id: 'animal_feed', name: 'Pasze', icon: '🌿', color: '#8bc34a' },
    { id: 'fuel', name: 'Paliwo', icon: '⛽', color: '#f44336' },
    { id: 'equipment', name: 'Sprzęt i części', icon: '🛠️', color: '#607d8b' },
    { id: 'animals', name: 'Zakup zwierząt', icon: '🐄', color: '#795548' },
    { id: 'maintenance', name: 'Naprawy i konserwacja', icon: '🔧', color: '#ff5722' },
    { id: 'taxes', name: 'Podatki i opłaty', icon: '🏛️', color: '#3f51b5' },
    { id: 'other_expenses', name: 'Inne koszty', icon: '📉', color: '#e91e63' }
  ]

  // Pobieranie transakcji w czasie rzeczywistym
  useEffect(() => {
    const q = query(
      collection(db, 'finance_transactions'),
      orderBy('date', 'desc')
    )
    
    const unsubscribe = onSnapshot(q, 
      (querySnapshot) => {
        const transactionsData = []
        querySnapshot.forEach((doc) => {
          const data = doc.data()
          transactionsData.push({ 
            id: doc.id, 
            ...data,
            date: data.date?.toDate?.() || data.date
          })
        })
        setTransactions(transactionsData)
        setLoading(false)
      },
      (error) => {
        console.error('Błąd przy pobieraniu transakcji:', error)
        setError(`Błąd przy pobieraniu danych: ${error.message}`)
        setLoading(false)
      }
    )

    return () => unsubscribe()
  }, [])

  // Pobieranie budżetów
  useEffect(() => {
    const q = query(collection(db, 'finance_budgets'))
    
    const unsubscribe = onSnapshot(q, 
      (querySnapshot) => {
        const budgetsData = []
        querySnapshot.forEach((doc) => {
          budgetsData.push({ id: doc.id, ...doc.data() })
        })
        setBudgets(budgetsData)
      },
      (error) => {
        console.error('Błąd przy pobieraniu budżetów:', error)
      }
    )

    return () => unsubscribe()
  }, [])

  // Dodawanie transakcji
  const addTransaction = async (transactionData) => {
    try {
      const docRef = await addDoc(collection(db, 'finance_transactions'), {
        ...transactionData,
        date: Timestamp.fromDate(new Date(transactionData.date)),
        createdAt: new Date(),
        amount: parseFloat(transactionData.amount)
      })
      return { success: true, id: docRef.id }
    } catch (error) {
      console.error('Błąd przy dodawaniu transakcji:', error)
      return { success: false, error: error.message }
    }
  }

  // Automatyczne dodawanie transakcji z innych modułów
  const addAutoTransaction = async (type, data) => {
    try {
      const transactionData = {
        type: type, // 'income' lub 'expense'
        category: data.category,
        amount: parseFloat(data.amount),
        description: data.description,
        source: data.source, // 'fields', 'animals', 'warehouse', 'garage'
        sourceId: data.sourceId,
        date: Timestamp.fromDate(new Date()),
        autoGenerated: true,
        createdAt: new Date()
      }

      const docRef = await addDoc(collection(db, 'finance_transactions'), transactionData)
      return { success: true, id: docRef.id }
    } catch (error) {
      console.error('Błąd przy automatycznym dodawaniu transakcji:', error)
      return { success: false, error: error.message }
    }
  }

  // Aktualizacja transakcji
  const updateTransaction = async (transactionId, updateData) => {
    try {
      const transactionRef = doc(db, 'finance_transactions', transactionId)
      await updateDoc(transactionRef, {
        ...updateData,
        lastUpdate: new Date(),
        amount: parseFloat(updateData.amount)
      })
      return { success: true }
    } catch (error) {
      console.error('Błąd przy aktualizacji transakcji:', error)
      return { success: false, error: error.message }
    }
  }

  // Usuwanie transakcji
  const deleteTransaction = async (transactionId) => {
    try {
      await deleteDoc(doc(db, 'finance_transactions', transactionId))
      return { success: true }
    } catch (error) {
      console.error('Błąd przy usuwaniu transakcji:', error)
      return { success: false, error: error.message }
    }
  }

  // Zarządzanie budżetami
  const addBudget = async (budgetData) => {
    try {
      const docRef = await addDoc(collection(db, 'finance_budgets'), {
        ...budgetData,
        createdAt: new Date(),
        amount: parseFloat(budgetData.amount),
        spent: 0
      })
      return { success: true, id: docRef.id }
    } catch (error) {
      console.error('Błąd przy dodawaniu budżetu:', error)
      return { success: false, error: error.message }
    }
  }

  const updateBudget = async (budgetId, updateData) => {
    try {
      const budgetRef = doc(db, 'finance_budgets', budgetId)
      await updateDoc(budgetRef, {
        ...updateData,
        lastUpdate: new Date()
      })
      return { success: true }
    } catch (error) {
      console.error('Błąd przy aktualizacji budżetu:', error)
      return { success: false, error: error.message }
    }
  }

  // Obliczenia finansowe
  const getFinancialSummary = () => {
    const currentMonth = new Date().getMonth()
    const currentYear = new Date().getFullYear()

    const monthlyIncome = transactions
      .filter(t => t.type === 'income' && 
        t.date?.getMonth?.() === currentMonth && 
        t.date?.getFullYear?.() === currentYear)
      .reduce((sum, t) => sum + (t.amount || 0), 0)

    const monthlyExpenses = transactions
      .filter(t => t.type === 'expense' && 
        t.date?.getMonth?.() === currentMonth && 
        t.date?.getFullYear?.() === currentYear)
      .reduce((sum, t) => sum + (t.amount || 0), 0)

    const totalIncome = transactions
      .filter(t => t.type === 'income')
      .reduce((sum, t) => sum + (t.amount || 0), 0)

    const totalExpenses = transactions
      .filter(t => t.type === 'expense')
      .reduce((sum, t) => sum + (t.amount || 0), 0)

    return {
      monthlyIncome,
      monthlyExpenses,
      monthlyBalance: monthlyIncome - monthlyExpenses,
      totalIncome,
      totalExpenses,
      totalBalance: totalIncome - totalExpenses
    }
  }

  return {
    transactions,
    budgets,
    incomeCategories,
    expenseCategories,
    loading,
    error,
    addTransaction,
    addAutoTransaction,
    updateTransaction,
    deleteTransaction,
    addBudget,
    updateBudget,
    getFinancialSummary
  }
}